"""create evaluations table

Revision ID: 1bad0da8867c
Revises: 22e783b381f8
Create Date: 2026-08-19 12:31:38.369467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bad0da8867c'
down_revision: Union[str, Sequence[str], None] = '22e783b381f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluations',
    sa.Column('evaluation_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=True),
    sa.Column('scores', sa.JSON(), nullable=True),
    sa.Column('advice', sa.JSON(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('evaluation_id')
    )
    op.create_index(op.f('ix_evaluations_company_id'), 'evaluations', ['company_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evaluations_company_id'), table_name='evaluations')
    op.drop_table('evaluations')
    # ### end Alembic commands ###
