"""add job_summary to companies

Revision ID: ac90a1a923cd
Revises: 1bad0da8867c
Create Date: 2026-08-26 15:53:21.464007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac90a1a923cd'
down_revision: Union[str, Sequence[str], None] = '1bad0da8867c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('job_summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'job_summary')
    # ### end Alembic commands ###
